import json, sys

sys.stdout.reconfigure(encoding="utf-8")

with open("notebooks/01_data_exploration.ipynb", "r", encoding="utf-8") as f:
    nb = json.load(f)

summary_md = [
    "## 12 · Tổng kết\n",
    "\n",
    "### 12.1 Tổng quan dữ liệu\n",
    "\n",
    "| Chỉ số | Giá trị | Nhận xét |\n",
    "|---|---|---|\n",
    "| Số dòng (train) | 700,000 | Đủ lớn cho modeling |\n",
    "| Số cột | 13 | 11 features (f0–f10) + treatment + conversion |\n",
    "| Kiểu dữ liệu | float64 (features), int64 (treatment, conversion) | Toàn bộ dạng số, không cần encoding |\n",
    "| Missing values | **0** | Dữ liệu rất sạch, không cần xử lý missing |\n",
    "| Duplicate rows | **13,750** (~1.96%) | Cần cân nhắc xử lý — có thể do bản chất dữ liệu (nhiều user có cùng feature pattern) |\n",
    "\n",
    "### 12.2 Vấn đề nghiêm trọng: Treatment Distribution\n",
    "\n",
    "> ⚠️ **CRITICAL**: Toàn bộ 700,000 dòng trong train set **chỉ chứa treatment=1** (100% treatment, 0% control).\n",
    "\n",
    "**Nguyên nhân**: File CSV gốc (~14M dòng) được sắp xếp theo cột `treatment` (treatment=1 đứng trước treatment=0). Pipeline `make_dataset.py` mặc định chỉ đọc **1,000,000 dòng đầu tiên** (`--read-rows 1000000`), dẫn đến toàn bộ sample chỉ chứa nhóm treatment.\n",
    "\n",
    "**Hậu quả**:\n",
    "- ❌ Không thể tính **uplift** (cần cả treatment và control)\n",
    "- ❌ Không thể so sánh conversion rate giữa 2 nhóm → Section 5 cho Δ = NaN\n",
    "- ❌ Biểu đồ phân phối theo treatment group (Section 10) và box-plot (Section 11) không có ý nghĩa\n",
    "\n",
    "**Giải pháp đề xuất**: Chạy lại `python -m src.data.make_dataset` với `--read-rows` đủ lớn (>= 5,000,000) hoặc **shuffle** dữ liệu trước khi sample, để đảm bảo cả 2 nhóm đều có mặt.\n",
    "\n",
    "### 12.3 Target Imbalance (Class Imbalance)\n",
    "\n",
    "| Target | Số lượng | Tỷ lệ |\n",
    "|---|---|---|\n",
    "| conversion = 0 | 696,671 | 99.52% |\n",
    "| conversion = 1 | 3,329 | **0.48%** |\n",
    "\n",
    "Target `conversion` cực kỳ **imbalanced** (tỷ lệ positive chỉ ~0.48%). Điều này ảnh hưởng lớn đến việc modeling:\n",
    "- Cần sử dụng các metric phù hợp: **AUUC**, **Qini coefficient**, chứ không phải accuracy\n",
    "- Có thể cần **stratified sampling** khi chia train/valid/test\n",
    "- Các thuật toán uplift cần được calibrate cẩn thận do positive rate rất thấp\n",
    "\n",
    "### 12.4 Phân tích Features\n",
    "\n",
    "#### Thống kê mô tả\n",
    "- Tất cả 11 features đều là **continuous** (float64)\n",
    "- Nhiều features có **median = 25th = 75th percentile** (ví dụ: f1, f2, f3, f4, f5, f7, f8, f9, f10), cho thấy phân phối rất **tập trung** với phần lớn giá trị giống nhau (có thể là giá trị mặc định hoặc đã được xử lý)\n",
    "- Chỉ **f0** và **f6** có sự phân tán rõ ràng giữa các quartile\n",
    "\n",
    "#### Skewness (Độ lệch)\n",
    "\n",
    "| Feature | Skewness | Đánh giá |\n",
    "|---|---|---|\n",
    "| f1 | **17.45** | Lệch phải cực mạnh |\n",
    "| f5 | **-7.55** | Lệch trái rất mạnh |\n",
    "| f4 | **7.49** | Lệch phải mạnh |\n",
    "| f10 | **5.19** | Lệch phải mạnh |\n",
    "| f9 | **4.65** | Lệch phải mạnh |\n",
    "| f7 | **4.51** | Lệch phải mạnh |\n",
    "| f3 | **-4.20** | Lệch trái mạnh |\n",
    "| f8 | **-2.69** | Lệch trái |\n",
    "| f2 | **1.70** | Lệch phải nhẹ |\n",
    "| f6 | **-1.15** | Lệch trái nhẹ |\n",
    "| f0 | **-1.03** | Gần symmetric |\n",
    "\n",
    "**Nhận xét**: Hầu hết features có |skewness| > 1, nhiều feature có skew cực cao (f1 = 17.45). Điều này cho thấy:\n",
    "- Phân phối rất **không chuẩn** (non-Gaussian)\n",
    "- Có thể cần **log transform** hoặc **power transform** trước khi đưa vào model\n",
    "- Tuy nhiên, các model tree-based (XGBoost, LightGBM) thường xử lý tốt dữ liệu skewed nên có thể không cần transform\n",
    "\n",
    "### 12.5 Correlation Analysis\n",
    "\n",
    "#### Top Correlation Pairs (giữa features)\n",
    "\n",
    "| Feature 1 | Feature 2 | Correlation | Mức độ |\n",
    "|---|---|---|---|\n",
    "| f5 | f7 | **-0.754** | Tương quan nghịch mạnh |\n",
    "| f8 | f9 | **-0.718** | Tương quan nghịch mạnh |\n",
    "| f4 | f8 | **-0.658** | Tương quan nghịch đáng kể |\n",
    "| f4 | f10 | **0.646** | Tương quan thuận đáng kể |\n",
    "| f4 | f9 | **0.611** | Tương quan thuận đáng kể |\n",
    "\n",
    "**Nhận xét**: Một số cặp features có **multicollinearity** khá cao (|r| > 0.6). Đối với linear models, cần cân nhắc loại bỏ bớt hoặc dùng PCA. Với tree-based models, multicollinearity ít ảnh hưởng hơn.\n",
    "\n",
    "#### Correlation với Target (conversion)\n",
    "\n",
    "| Feature | Correlation | Nhận xét |\n",
    "|---|---|---|\n",
    "| f4 | **0.354** | Tương quan thuận cao nhất |\n",
    "| f9 | **0.324** | Tương quan thuận cao |\n",
    "| f8 | **-0.248** | Tương quan nghịch |\n",
    "| f3 | **-0.174** | Tương quan nghịch nhẹ |\n",
    "| f1 | **0.135** | Tương quan thuận nhẹ |\n",
    "| f2 | **0.005** | Gần như không tương quan |\n",
    "\n",
    "**Nhận xét**: Tất cả correlations với target đều khá thấp (|r| < 0.4), điều này phổ biến trong bài toán uplift modeling. Features **f4** và **f9** có khả năng đóng vai trò quan trọng nhất trong việc dự đoán conversion.\n",
    "\n",
    "### 12.6 Tóm tắt & Khuyến nghị\n",
    "\n",
    "| # | Vấn đề | Mức độ | Hành động |\n",
    "|---|---|---|---|\n",
    "| 1 | **Thiếu control group** | 🔴 Critical | Rebuild dataset với đầy đủ cả treatment & control (shuffle trước khi sample hoặc tăng `--read-rows`) |\n",
    "| 2 | **Target imbalance** (~0.48%) | 🟡 Medium | Sử dụng metric phù hợp (AUUC, Qini); stratified split |\n",
    "| 3 | **Features rất skewed** | 🟡 Medium | Cân nhắc transform nếu dùng linear model; tree-based model xử lý tốt |\n",
    "| 4 | **Multicollinearity** (f5-f7, f8-f9) | 🟢 Low | Ít ảnh hưởng với tree-based models |\n",
    "| 5 | **Duplicate rows** (~2%) | 🟢 Low | Kiểm tra xem có cần remove hay do bản chất dữ liệu |\n",
    "| 6 | **Missing values** | ✅ None | Dữ liệu sạch, không cần xử lý |\n",
]

# Replace the last cell
nb["cells"][-1]["source"] = summary_md

with open("notebooks/01_data_exploration.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print("Summary updated successfully!")
